#!/bin/bash

ARCH=$(uname -m)
if [[ "$ARCH" == "x86_64" ]]; then
    ARCHITECTURE="x86"
elif [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
    ARCHITECTURE="arm64"
else
    echo "Unsupported architecture: $ARCH"
    exit 1
fi

EXEC="./build/popcat_help_you_search_${ARCHITECTURE}"
$EXEC